### ISSUE TITLE
Android 15 Crash rate high, version is 1.4.0

### ISSUE THREAD

**Issue by simple-way** [tiktok/tiktok-business-android-sdk#17]
I upgrade tiktok business android sdk to newest to 1.4.0, however I found my app Google console crash rate gets higher.
From the backtrace, I found TTHierarchyHelper line 116,
```java
try {
    TTEDPEventTrack.trackClick(className, event.getRawX(), event.getRawY(), rootView.get().getMeasuredWidth(),
            rootView.get().getMeasuredHeight(), rootView.get() instanceof TextView ? ((TextView) (rootView.get())).getText().toString() : "",
            activity.get().getClass().getSimpleName(), TTHierarchyHelper.getViewHierarchy(new WeakReference<>(activity.get().getWindow().getDecorView()), page_detail_upload_deep_count),
            getViewHierarchyCount(new WeakReference<>(activity.get().getWindow().getDecorView())),
            System.currentTimeMillis() - touchDown);
} catch (Throwable e) {

}
```
Although try catch the code, it still crash on native, Please have a look at this and fix it on a new version.

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 2844 >>> com.my.app <<<

backtrace:
  #00  pc 0x000000000005dec4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #01  pc 0x000000000009dd00  /system/lib64/libinput.so (__ubsan_handle_pointer_overflow_minimal_abort+100)
  #02  pc 0x00000000000a0218  /system/lib64/libinput.so (android::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, android::MotionEvent const&)+1920)
  #03  pc 0x00000000000f2a08  /system/lib64/libandroid_runtime.so (android::validatePointerIndex(_JNIEnv*, int, android::MotionEvent const&)+408)
  #04  pc 0x00000000000f1d2c  /system/lib64/libandroid_runtime.so (android::android_view_MotionEvent_nativeGetRawAxisValue(_JNIEnv*, _jclass*, long, int, int, int)+44)
  #05  pc 0x000000000038c4c0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+96)
  #06  pc 0x0000000000cdac58  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.view.MotionEvent.getRawY+504)
  #07  pc 0x00000000006b9d24  /data/app/~~ds8mW7BT-wFMM15_72ve7g==/com.my.app-qz9KPKz16udeRJLi4P_pbg==/oat/arm64/base.odex (com.tiktok.appevents.edp.TTHierarchyHelper$1$1.run+116)
  #08  pc 0x000000000052386c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.Executors$RunnableAdapter.call+60)
  #09  pc 0x00000000005b12e4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.FutureTask.run+164)
  #10  pc 0x0000000000630110  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run+128)
  #11  pc 0x00000000005fa958  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+680)
  #12  pc 0x00000000005f8458  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+56)
  #13  pc 0x00000000004d2fb0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Thread.run+64)
  #14  pc 0x0000000000368774  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612)
  #15  pc 0x0000000000353f24  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+132)
  #16  pc 0x0000000000947748  /apex/com.android.art/lib64/libart.so (art::detail::ShortyTraits<(char)86>::Type art::ArtMethod::InvokeInstance<(char)86>(art::Thread*, art::ObjPtr<art::mirror::Object>, art::detail::ShortyTraits<>::Type...)+60)
  #17  pc 0x0000000000636e80  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1344)
  #18  pc 0x0000000000636930  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallbackWithUffdGc(void*)+8)
  #19  pc 0x0000000000070578  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+200)
  #20  pc 0x0000000000061910  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

**Comment by zhangketong05** [comment]
Thanks for the feedback. Does this crash only occur on Android 15? Are there similar crashes on other versions?

**Comment by simple-way** [comment]
Thanks for your reply. However, I've already released the latest version, rolling back the SDK version to ​​1.3.7​​. I found that this version doesn't include the problematic code, so it should avoid the issue.

​​Should this be fine? Rolling back to 1.3.7 won't affect the accuracy of online data, right?​​

**Comment by zhangketong05** [comment]
OK, you can roll back to version 1.3.7, which will not affect online data.❤️

**Comment by simple-way** [comment]
Thanks, I will close this issus

**Comment by rgfneves** [comment]
Dear,

Although we installed the latest version 1.5.0 this crash is still happening!
